# Generated by Django 3.1.13 on 2021-07-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIconsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='mysite_socialiconspluginmodel', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('class_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
